name = "MLDataUtils"
uuid = "cc2ba9b6-d476-5e6d-8eaf-a92d5412d41d"
authors = ["Christof Stocker <stocker.christof@gmail.com>"]
version = "0.5.2"

[deps]
DataFrames = "a93c6f00-e57d-5684-b7b6-d8193f3e46c0"
DelimitedFiles = "8bb1440f-4735-579b-a4ab-409b98df4dab"
LearnBase = "7f8f8fb0-2700-5f03-b4bd-41f8cfc144b6"
MLDataPattern = "9920b226-0b2a-5f5f-9153-9aa70a013f8b"
MLLabelUtils = "66a33bbf-0c2b-5fc8-a008-9da813334f0a"
Statistics = "10745b16-79ce-11e8-11f9-7d13ad32a3b2"
StatsBase = "2913bbd2-ae8a-5f71-8c99-4fb6c76f3a91"

[compat]
DataFrames = "0.19, 0.20, 0.21, 0.22"
LearnBase = "0.2, 0.3"
MLDataPattern = "0.5"
MLLabelUtils = "0.4, 0.5"
StatsBase = "0.25, 0.26, 0.27, 0.28, 0.29, 0.30, 0.31, 0.32, 0.33"
julia = "1"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"
UnicodePlots = "b8865327-cd53-5732-bb35-84acbb429228"

[targets]
test = ["Test", "UnicodePlots"]
